services:
  - type: web
    name: quiniela-app
    runtime: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/quiniela-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d8lnlo0js32c73b1g7ng-a.oregon-postgres.render.com:5432/quiniela_risv
      - key: DB_USER
        value: admin
      - key: DB_PASS
        value: v4HFnnVCf3YM81lTKUPgTocTf13OUnYw