# Nombre de la aplicación y puerto
spring.application.name=quiniela
server.port=8080

# Configuración de la Base de Datos (PostgreSQL)
# Usa variables de entorno (${VARIABLE:valor_por_defecto}) para que sea dinámico
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8lnlo0js32c73b1g7ng-a.oregon-postgres.render.com/quiniela_risv}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:v4HFnnVCf3YM81lTKUPgTocTf13OUnYw}

# Configuración de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Formatear el SQL en la consola para leerlo mejor mientras pruebas
spring.jpa.properties.hibernate.format_sql=true